### ISSUE TITLE
Add in per-os version build files

### ISSUE THREAD

**Issue by JasonYao** [JasonYao/pydotfiles#81]
right now, we do a check in our default settings for macos that looks like this:

```python
def template_os_default_setting(data: DefaultSettings) -> str:
    if not data.should_run(get_current_mac_version()):
        # blah blah blah
        pass
    pass
```

This comes with two major drawback:
1. Linux build runners are unable to actually build macos build packages since there's no `current_mac_version`
2. Presuming that we have multiple macos versions, it'd be nice to have per os version configs.
  - Currently, my personal mac is on `Big Sur`, while my work mac is on whatever the latest version is. This could be solved by adding in a field for os version in the profile manifest.

## Before
```yaml
version: "alpha"
schema: "manifest"
profiles:
  work:
    - core
    - work
  personal:
    - core
    - dev
    - personal
```

## After
```yaml
version: "alpha"
schema: "manifest"
profiles:
  work:
    dependencies:
      - core
      - work
    os_versions:
      macos:
        - 11.7
        - latest
      linux
        - <insert glinux version here>
  personal:
    dependencies:
      - core
      - dev
      - personal
    os_versions:
      macos:
        - 11.5
        - latest
      linux
        - <insert whatever raspberry-pi or other personal project linux version here>
```
